### ISSUE TITLE
License is completely void

### ISSUE THREAD

**Issue by vswarte** [Pear0533/FLVER_Editor#86]
https://github.com/Pear0533/FLVER_Editor/blob/master/LICENSE is completely void because a large portion of the code is actually coming from this project: https://github.com/asasasasasbc/FLVER_Editor/

You can't just take someone elses unlicensed code (which means they retain all rights) and license it as your own.

**Comment by Pear0533** [comment]
A large portion of the code in the program has actually been completely re-written, and will be fully re-written by the time me and Natsu are completed with the re-write process. So the license will be there to stay. I will also be implementing a method to handle OODLE, since we indeed cannot have that in the source repository due to legal reasons.

**Comment by vswarte** [comment]
A lot of the code also hasn't. One such example is: https://github.com/Pear0533/FLVER_Editor/blob/master/FLVER_Editor/Transform3D.cs vs https://github.com/asasasasasbc/FLVER_Editor/blob/master/MySFformat/Transform3D.cs

The logic and the comments align 1-to-1 and all changes are super superficial.
Adding a bunch of newlines and `{` `}` is not a rewrite. It seems a lot of this is just minimum-effort changes (possibly automated).

**Comment by vswarte** [comment]
Links will probably break since I'm referencing master but for archival purposes I've screencapped both the original code (first) and Pear's (second):
![lmao](https://user-images.githubusercontent.com/6827387/235435575-3f6f9198-62cf-4c69-a4a7-ebcac7277cb2.PNG)
![pears](https://user-images.githubusercontent.com/6827387/235435581-271f1955-f34d-4ae3-8985-889ecea1b5f2.PNG)

**Comment by vswarte** [comment]
There's also https://github.com/Pear0533/FLVER_Editor/blob/master/FLVER_Editor/Vector3D.cs vs https://github.com/asasasasasbc/FLVER_Editor/blob/master/MySFformat/Vector3D.cs

**Original**
![original-2](https://user-images.githubusercontent.com/6827387/235436089-0c8af751-464f-4562-aeea-21461526db7c.PNG)


**Pear's**
![pears-2](https://user-images.githubusercontent.com/6827387/235436106-e7f06601-63c6-40d6-b608-04ff147ad276.PNG)

From what I can tell these are essential to the functioning of ~~your~~ the tool, it simply wouldn't exist without.

It's kinda funny that you start it's a tiny portion left over everywhere on Discord. I know that isn't true but nobody will check the code so 🤷🏻.
![image](https://user-images.githubusercontent.com/6827387/235436428-83fd2c4a-51c4-48c7-af34-0a9c0859e284.png)

I don't care that you grift with boosted Balenciaga on Discord but you can't just slap your own license on it and have it be legally binding in any capacity 👍🏻

**Comment by Pear0533** [comment]
I think that it was just a simple case of me assuming that I had re-written all of the original code for everything because it was the first major project that I had worked on, and it was a private tool at the time. I accepted the fact that the only code re-written was code for completely new/improved features, everything else, upon closer inspection, is indeed the same.

I have removed the license as you requested, and apologize for my ignorance. I will not place a license on this tool until all of the code genuinely is re-written from scratch as it should be.
